### ISSUE TITLE
Cant compile ulp_i2c_bitbang example, other compiled nice

### ISSUE THREAD

**Issue by yankobogdan** [duff2013/arduino_ulp#7]
python "C:\Users\bogdan\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/ulp/esp32ulp_build_recipe.py" -b C:\Users\bogdan\AppData\Local\Temp\arduino_build_548103 -p C:\Users\bogdan\Documents\Arduino\hardware\espressif\esp32 --DF_CPU=240000000L --DARDUINO=10801 --DARDUINO_=ESP32_DEV --DARDUINO_ARCH_=ESP32 --DARDUINO_BOARD="ESP32_DEV" --DARDUINO_VARIANT="doitESP32devkitV1"
ULP Assembly File(s) Detected: ['i2c.s', 'i2c_dev.s', 'stack.s']
C:\Users\bogdan\Documents\Arduino\hardware\espressif\esp32\tools\esp32ulp-elf-binutils\bin\esp32ulp-elf-ld -o ulp_main.elf -A elf32-esp32ulp -Map=ulp_main.map -T ulp_main.common.ld i2c.ulp.o i2c_dev.ulp.o stack.ulp.o
exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.

Do you have any ideas?

**Comment by duff2013** [comment]
You need to increase ulp memory, see the comment in the example I just [uploaded](https://github.com/duff2013/arduino_ulp/blob/master/ulp_examples/ulp_i2c_bitbang/ulp_i2c_bitbang.ino)
