### ISSUE TITLE
Interaction with main CPU

### ISSUE THREAD

**Issue by yankobogdan** [duff2013/arduino_ulp#8]
Can you show pls example of code with interaction to the main CPU. Like for example: 
WiFI conection->ULP activate-> main CPU off->ULP event handler-> main CPU wake up-> Sending var from ULP to main CPU
I just tried to add WiFI.SmartConfig() function to ulp_README example and nothing compiled.

Thanks for your time!

**Comment by duff2013** [comment]
Sorry haven't used the ulp with those modules, you'll have to investigate that yourself.
